-- todo versionar com flyway
INSERT INTO UF (CD_UF, NM_UF, SG_UF, NM_REGIAO) VALUES
                                                    (1, 'Acre', 'AC', 'NORTE'),
                                                    (2, 'Alagoas', 'AL', 'NORDESTE'),
                                                    (3, 'Amapá', 'AP', 'NORTE'),
                                                    (4, 'Amazonas', 'AM', 'NORTE'),
                                                    (5, 'Bahia', 'BA', 'NORDESTE'),
                                                    (6, 'Ceará', 'CE', 'NORDESTE'),
                                                    (7, 'Distrito Federal', 'DF', 'CENTRO_OESTE'),
                                                    (8, 'Espírito Santo', 'ES', 'SUDESTE'),
                                                    (9, 'Goiás', 'GO', 'CENTRO_OESTE'),
                                                    (10, 'Maranhão', 'MA', 'NORDESTE'),
                                                    (11, 'Mato Grosso', 'MT', 'CENTRO_OESTE'),
                                                    (12, 'Mato Grosso do Sul', 'MS', 'CENTRO_OESTE'),
                                                    (13, 'Minas Gerais', 'MG', 'SUDESTE'),
                                                    (14, 'Pará', 'PA', 'NORTE'),
                                                    (15, 'Paraíba', 'PB', 'NORDESTE'),
                                                    (16, 'Paraná', 'PR', 'SUL'),
                                                    (17, 'Pernambuco', 'PE', 'NORDESTE'),
                                                    (18, 'Piauí', 'PI', 'NORDESTE'),
                                                    (19, 'Rio de Janeiro', 'RJ', 'SUDESTE'),
                                                    (20, 'Rio Grande do Norte', 'RN', 'NORDESTE'),
                                                    (21, 'Rio Grande do Sul', 'RS', 'SUL'),
                                                    (22, 'Rondônia', 'RO', 'NORTE'),
                                                    (23, 'Roraima', 'RR', 'NORTE'),
                                                    (24, 'Santa Catarina', 'SC', 'SUL'),
                                                    (25, 'São Paulo', 'SP', 'SUDESTE'),
                                                    (26, 'Sergipe', 'SE', 'NORDESTE'),
                                                    (27, 'Tocantins', 'TO', 'NORTE');